version: '3'

services:
  mongodb:
    image: 'mongo'
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=postkitadmin
    volumes:
      - postkit-mongo-volume:/data/db
  mongo-express:
    image: 'mongo-express'
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=postkitadmin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb


volumes:
  postkit-mongo-volume:
    driver: local
